server.port=8080

spring.main.allow-circular-references=true

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

spring.datasource.url=jdbc:h2:mem:interview
spring.datasource.username=root
spring.datasource.password=123456
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.platform=h2